//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path to output file&gt;.
        /// </summary>
        public static string Argument_PathToOutput {
            get {
                return ResourceManager.GetString("Argument_PathToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path to source file&gt;.
        /// </summary>
        public static string Argument_PathToSource {
            get {
                return ResourceManager.GetString("Argument_PathToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description for the $commandname$ Command.
        /// </summary>
        public static string Description_$commandname$ {
            get {
                return ResourceManager.GetString("Description_$commandname$", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already Exists: {0}.
        /// </summary>
        public static string Format_FileAlreadExists {
            get {
                return ResourceManager.GetString("Format_FileAlreadExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string Format_FileNotFound {
            get {
                return ResourceManager.GetString("Format_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Format_OptionUsage {
            get {
                return ResourceManager.GetString("Format_OptionUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $commandname$.
        /// </summary>
        public static string Name_$commandname$ {
            get {
                return ResourceManager.GetString("Name_$commandname$", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Help.
        /// </summary>
        public static string OptionDescription_Help {
            get {
                return ResourceManager.GetString("OptionDescription_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the output file.
        /// </summary>
        public static string OptionDescription_Output_$commandname$ {
            get {
                return ResourceManager.GetString("OptionDescription_Output_$commandname$", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pah to a source file.
        /// </summary>
        public static string OptionDescription_Source_$commandname$ {
            get {
                return ResourceManager.GetString("OptionDescription_Source_$commandname$", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OptionLongName_Output {
            get {
                return ResourceManager.GetString("OptionLongName_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string OptionLongName_Source {
            get {
                return ResourceManager.GetString("OptionLongName_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Help (?).
        /// </summary>
        public static string OptionName_Help {
            get {
                return ResourceManager.GetString("OptionName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string OptionShortName_Output {
            get {
                return ResourceManager.GetString("OptionShortName_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string OptionShortName_Source {
            get {
                return ResourceManager.GetString("OptionShortName_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Help.
        /// </summary>
        public static string OptionUsage_Help {
            get {
                return ResourceManager.GetString("OptionUsage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Source &lt;path to json file&gt; -Output &lt;path to new xml file&gt;.
        /// </summary>
        public static string UsageFragment_$commandname$ {
            get {
                return ResourceManager.GetString("UsageFragment_$commandname$", resourceCulture);
            }
        }
    }
}
