version: 1.0.{build}

branches:
  only:
    - master

# scripts to run before build
before_build:
nuget restore
rd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Amazon Web Services LLC" /s /q

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: PingoConsole.sln

after_test:
  - ps: .\.nuget\pack.ps1

artifacts:
  - path: '.\*.nupkg'
    
 

#uncomment to publish to NuGet
#deploy:
#  provider: NuGet
#  api_key:
#    secure: n/2gZwCGLcoLBr5nGu5akS0IFQ1YHciI6Wz0NGC+1mLTUtO08Uy+TWn7OtyLG9v3
#  artifact: /.*\.nupkg/