//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pingo.JsonConverters.Commands.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pingo.JsonConverters.Commands.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path to Json file&gt;.
        /// </summary>
        public static string Argument_PathToJson {
            get {
                return ResourceManager.GetString("Argument_PathToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path to Json Schema file&gt;.
        /// </summary>
        public static string Argument_PathToJsonSchema {
            get {
                return ResourceManager.GetString("Argument_PathToJsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path to xml file&gt;.
        /// </summary>
        public static string Argument_PathToXml {
            get {
                return ResourceManager.GetString("Argument_PathToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a Json.Net XML schema file to XML.
        /// </summary>
        public static string Description_Json2Xml {
            get {
                return ResourceManager.GetString("Description_Json2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does a json schema validation for a given json file..
        /// </summary>
        public static string Description_JsonSchema {
            get {
                return ResourceManager.GetString("Description_JsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts an XML file to a Json.Net schema type json file.
        /// </summary>
        public static string Description_Xml2Json {
            get {
                return ResourceManager.GetString("Description_Xml2Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string Format_OptionUsage {
            get {
                return ResourceManager.GetString("Format_OptionUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json2Xml.
        /// </summary>
        public static string Name_Json2Xml {
            get {
                return ResourceManager.GetString("Name_Json2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JsonSchema.
        /// </summary>
        public static string Name_JsonSchema {
            get {
                return ResourceManager.GetString("Name_JsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml2Json.
        /// </summary>
        public static string Name_Xml2Json {
            get {
                return ResourceManager.GetString("Name_Xml2Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Help.
        /// </summary>
        public static string OptionDescription_Help {
            get {
                return ResourceManager.GetString("OptionDescription_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the new XML file..
        /// </summary>
        public static string OptionDescription_Output_Json2Xml {
            get {
                return ResourceManager.GetString("OptionDescription_Output_Json2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the new Json file..
        /// </summary>
        public static string OptionDescription_Output_Xml2Json {
            get {
                return ResourceManager.GetString("OptionDescription_Output_Xml2Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to a json schema file..
        /// </summary>
        public static string OptionDescription_Schema_Json {
            get {
                return ResourceManager.GetString("OptionDescription_Schema_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pah to an Json file..
        /// </summary>
        public static string OptionDescription_Source_Json2Xml {
            get {
                return ResourceManager.GetString("OptionDescription_Source_Json2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pah to an XML file..
        /// </summary>
        public static string OptionDescription_Source_Xml2Json {
            get {
                return ResourceManager.GetString("OptionDescription_Source_Xml2Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OptionLongName_Output {
            get {
                return ResourceManager.GetString("OptionLongName_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string OptionLongName_Schema {
            get {
                return ResourceManager.GetString("OptionLongName_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string OptionLongName_Source {
            get {
                return ResourceManager.GetString("OptionLongName_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Help (?).
        /// </summary>
        public static string OptionName_Help {
            get {
                return ResourceManager.GetString("OptionName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        public static string OptionShortName_Output {
            get {
                return ResourceManager.GetString("OptionShortName_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string OptionShortName_Source {
            get {
                return ResourceManager.GetString("OptionShortName_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Help.
        /// </summary>
        public static string OptionUsage_Help {
            get {
                return ResourceManager.GetString("OptionUsage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Source &lt;path to json file&gt; -Output &lt;path to new xml file&gt;.
        /// </summary>
        public static string UsageFragment_Json2Xml {
            get {
                return ResourceManager.GetString("UsageFragment_Json2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Source &lt;path to json file&gt; -Schema &lt;path to json schema file&gt;.
        /// </summary>
        public static string UsageFragment_JsonSchema {
            get {
                return ResourceManager.GetString("UsageFragment_JsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Source &lt;path to xml file&gt; -Output &lt;path to new json file&gt;.
        /// </summary>
        public static string UsageFragment_Xml2Json {
            get {
                return ResourceManager.GetString("UsageFragment_Xml2Json", resourceCulture);
            }
        }
    }
}
